#!/bin/bash

go build -o _dataprepper
chmod +x _dataprepper
./_dataprepper "$@"

output_file=$(echo "$@" | grep -oP '(?<=-o\s)[^\s]+' | tail -1)
data_folder=$(echo "$@" | grep -oP '(?<=-d\s)[^\s]+' | tail -1)
trap '[[ -n "$output_file" ]] && rm -f "$output_file"; [[ -n "$data_folder" ]] && rm -rf "$data_folder" && rm _datprepper; exit' SIGTERM

rm _dataprepper

